language: java
sudo: false

jdk:
  - openjdk8

install: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/jvm'
    - '$HOME/maven'

after_success:
  - mvn clean test org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report